USE [master]
GO

/****** Object:  Database [eggX_users]    Script Date: 3/10/2022 2:48:58 PM ******/
CREATE DATABASE [eggX_users]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eggX_users', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\eggX_users.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'eggX_users_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\eggX_users_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eggX_users].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eggX_users] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eggX_users] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eggX_users] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eggX_users] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eggX_users] SET ARITHABORT OFF 
GO

ALTER DATABASE [eggX_users] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eggX_users] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eggX_users] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eggX_users] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eggX_users] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eggX_users] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eggX_users] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eggX_users] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eggX_users] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eggX_users] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eggX_users] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eggX_users] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eggX_users] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eggX_users] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eggX_users] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eggX_users] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eggX_users] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eggX_users] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [eggX_users] SET  MULTI_USER 
GO

ALTER DATABASE [eggX_users] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eggX_users] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eggX_users] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [eggX_users] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [eggX_users] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [eggX_users] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [eggX_users] SET QUERY_STORE = OFF
GO

ALTER DATABASE [eggX_users] SET  READ_WRITE 
GO


